#  Codejam Practice Session 2018

In [1]:
import string
import numpy
import random

## Task 1 Number Guessing

__Problem__

This problem is a well-known classic; we present it primarily as an opportunity for you to try out the interactive judging system.

We are thinking of an integer $P$ within the range $\big( A,B \big]$ — that is, $A < P \leq B$. 

You have $N$ tries to guess our number. 

After each guess that is not correct, we will tell you whether $P$ is higher or lower than your guess.

__Input and output__

This problem is interactive, which means that the concepts of input and output are different than in standard Code Jam problems. 

You will interact with a separate process that both provides you with information and evaluates your responses. 

All information comes into your program via standard input; anything that you need to communicate should be sent via standard output. 

Remember that many programming languages buffer the output by default, so make sure your output actually goes out (for instance, by flushing the buffer) before blocking to wait for a response. 

See the __FAQ__ for an explanation of what it means to flush the buffer. 

Anything your program sends through standard error is ignored, but it might consume some memory and be counted against your memory limit, so do not overflow it. 

To help you debug, a local testing tool script (in Python) is provided at the very end of the problem statement.

Initially, your program should read a single line containing a single integer $T$ indicating the number of test cases. 

Then, you need to process $T$ test cases.

For each test case, your program will read a single line with two integers $A$ and $B$, representing the exclusive lower bound and inclusive upper bound, as described above. 

In the next line, you will read a single integer $N$, representing the maximum number of guesses you can make. 

Your program will process up to $N$ exchanges with our judge.

For each exchange, your program needs to use standard output to send a single line with one integer $Q$: your guess. 

In response to your guess, the judge will print a single line with one word to your input stream, which your program must read through standard input. 

The word will be 

- `CORRECT` if your guess is correct, 

- `TOO_SMALL` if your guess is less than the correct answer, and 

- `TOO_BIG` if your guess is greater than the correct answer. 

Then, you can start another exchange.

If your program gets something wrong (e.g., wrong output format, or out-of-bounds values), the judge will send `WRONG_ANSWER` to your input stream and it will not send any other output after that. 

If your program continues to wait for the judge after receiving `WRONG_ANSWER`, your program will time out, resulting in a `Time Limit Exceeded Error`. 

Notice that it is your responsibility to have your program exit in time to receive the appropriate verdict (`Wrong Answer`, `Runtime Error`, etc.) instead of a `Time Limit Exceeded Error`. 

As usual, if the total time or memory is exceeded, or your program gets a runtime error, you will receive the appropriate verdict.

If your test case is solved within $N$ tries, you will receive the `CORRECT` message from the judge, as mentioned above, 

and then continue to get input (a new line with two integers A and B, etc.) for the next test case. 

After $N$ tries, if the test case is not solved, the judge will print `WRONG_ANSWER` and then stop sending output to your input stream.

You should not send additional information to the judge after solving all test cases. 

In other words, if your program keeps printing to standard output after receiving `CORRECT` for the last test case, you will get a `Wrong Answer` judgment.

__Limits__

$1 \leq T \leq 20$.

$A = 0. \ N = 30$.

Time limit: 10 seconds per test set.

Memory limit: 1GB.

Test set 1 (Visible)

$B = 30$.

Test set 2 (Hidden)

$B = 109$.


__Sample interaction__

Here is a piece of pseudocode that demonstrates an interaction for one test set. 

Suppose there are three test cases in this test set. 

The pseudocode first reads an integer $t$, representing the number of test cases. 

Then the first test case begins. 

Suppose the correct answer $P$ is 9 for the first test case. 

The pseudocode first reads three integers $a, b$, and $n$, representing the guessing range and maximum number of tries, respectively, and then outputs a guess 30. 

Since 30 is greater than 9, the string `TOO_BIG` is received through stdin from the judge. 

Then the pseudocode guesses 5 and receives `TOO_SMALL` in response. 

The guess 10 is subsequently printed to stdout which is again too big. 

Finally the pseudocode guesses 9, and receives CORRECT because 9 is the correct answer.

-  t = read_int()         // reads 3 into t
  
-  a, b = read_two_int()  // reads 0 into a and 30 into b; note that 0 30 is one line
  
-  n = read_int()         // reads 30 into n
  
-  print 30 to stdout     // guesses 30
  
-  flush stdout
  
-  string s = read()      // because 30 > 9, reads TOO_BIG into s
  
-  print 5 to stdout      // guesses 5
  
-  flush stdout
  
-  s = read()             // reads TOO_SMALL into s since 5 < 9
  
-  print 10 to stdout     // guesses 10
  
-  flush stdout
  
-  s = readline()         // reads TOO_BIG into s since 10 > 9
  
-  print 9 to stdout      // guesses 9
  
-  flush stdout
  
-  s = read()             // reads CORRECT into s
  
The second test case shows what happens if the code continues to read from stdin after the judge stops sending info.

In this example, the contestant guesses 31, which is outside the range (0, 30]. 

As a result, the judging system sends `WRONG_ANSWER` to the input stream of the pseudocode and stops sending anything after that. 

However, after reading `WRONG_ANSWER` into string $s$, the code continues to read for the next test case. 

Since there is nothing in the input stream (judge has stopped sending info), the code hangs and will eventually receive a `Time Limit Exceeded Error`.

-  a, b = read_two_int()  // reads 0 into a and 30 into b; note that 0 30 is one line
  
-  n = read_int()         // reads 30 into n
  
-  print 31 to stdout     // guesses 31
  
-  flush stdout
  
-  string s = read()      // reads WRONG_ANSWER
  
-  a, b = read_two_int()  // tries to read for the third test case but hangs since
  
-                         // judge has stopped sending info to stdin
                         
If the code in the example above exits immediately after reading `WRONG_ANSWER`, it will receive a `Wrong Answer` judgment instead.

-  a, b = read_two_int()  // reads 0 into a and 30 into b; note that 0 30 is one line
  
-  n = read_int()         // reads 30 into n
  
-  print 31 to stdout     // guesses 31
  
-  flush stdout
  
-  string s = read()      // reads WRONG_ANSWER
  
-  exit                   // receives a Wrong Answer judgment
  
Local Testing Tool

To better facilitate local testing, we provide you the following script. 

Instructions are included inside the script. 

Please be advised that although the testing tool is intended to simulate the judging system, it is NOT the real judging system and might behave differently.

## Task 1 Decision 

Let's imitate dialogues with this interactive system.

In [1]:
while True: 
    try:
        T = int(input("Indicate the number of test cases in the range [1,20] "))
        if T in range(1,21):
            print("Thank you", flush=True)
            break 
        else:
            print("Please enter only integers in the mentioned range!", flush=True)
            continue
    except ValueError:
        print("Please enter only integers!", flush=True)

CORRECT_GUESS_LIST = []
s = "Indicate two integers A and B (the exclusive lower bound and inclusive upper bound)" + \
    "\n" + "in the format <A><white space><B>: "
for i in range(T):
    while True:
        try:
            S = input(s)
            N = int(input("Indicate the number of guesses [1,30] "))

            if (len(S.split()) == 2) and (int(S.split()[0]) > -1) \
            and (int(S.split()[1]) > int(S.split()[0])) and (N < 31 and N > 0):
                A, B = int(S.split()[0]),int(S.split()[1])
                break
            else: 
                print("Please enter two integers in the mentioned range!", flush=True)
                continue
        except ValueError:
            print("Please enter only integers!", flush=True)
            
    P = random.randint(A+1, B)
    
    for j in range(N):
        try:
            Q = int(input("Try to guess the number "))
        except ValueError:
            print("Please enter only integers!", flush=True) 
        
        if Q not in range(A+1, B+1):
            print("WRONG_ANSWER", flush=True)
            break
            
        else:        
            if Q < P:
                print("TOO_SMALL", flush=True)        
            elif Q > P:
                print("TOO_BIG", flush=True)
            elif Q == P:
                print("CORRECT", flush=True)
                CORRECT_GUESS_LIST.append(Q)
                break
                
print(CORRECT_GUESS_LIST, flush=True)

Indicate the number of test cases in the range [1,20] 1.8
Please enter only integers!
Indicate the number of test cases in the range [1,20] 3
Thank you
Indicate two integers A and B (the exclusive lower bound and inclusive upper bound)
in the format <A><white space><B>: 1 20
Indicate the number of guesses [1,30] 5
Try to guess the number 10
TOO_BIG
Try to guess the number 5
TOO_SMALL
Try to guess the number 8
TOO_BIG
Try to guess the number 7
TOO_BIG
Try to guess the number 6
CORRECT
Indicate two integers A and B (the exclusive lower bound and inclusive upper bound)
in the format <A><white space><B>: 1 8
Indicate the number of guesses [1,30] 3
Try to guess the number 4
CORRECT
Indicate two integers A and B (the exclusive lower bound and inclusive upper bound)
in the format <A><white space><B>: 1 30
Indicate the number of guesses [1,30] 10
Try to guess the number 15
TOO_SMALL
Try to guess the number 23
TOO_SMALL
Try to guess the number 27
CORRECT
[6, 4, 27]


The possible program as an answer.

In [2]:
T = int(input())
try:
    for i in range(T):
        S = input()
        S = [int(s) for s in S.split()]
        A, B = S[0] + 1, S[1]
        N = int(input())
        for j in range(N):
            Q = A + (B - A) // 2
            print(Q, flush=True)
            
            Answer = input()
            if Answer == "WRONG_ANSWER":
                raise StopIteration
            elif Answer == "CORRECT":
                break
            elif Answer == "TOO_SMALL":
                if (B - A)// 2 == 0:
                    A = A + 1
                else:
                    A = A + (B - A) // 2
            elif Answer == "TOO_BIG":
                if (B - A ) // 2 == 0:
                    B = B - 1
                else:                
                    B = B - (B - A) // 2 
                
except StopIteration: pass

3
1 20
10
11
TOO_SMALL
15
TOO_SMALL
17
TOO_SMALL
18
CORRECT
1 5
3
3
TOO_BIG
3
TOO_BIG
2
CORRECT
1 7
4
4
TOO_BIG
3
CORRECT


## Task 2 Senate Evacuation

__Problem__

A small fire started in the senate room, and it needs to be evacuated!

There are some senators in the senate room, each of whom belongs to of one of $N$ political parties. 

Those parties are named after the first $N$ (uppercase) letters of the English alphabet.

The emergency door is wide enough for up to two senators, so in each step of the evacuation, 

you may choose to remove either one or two senators from the room.

The senate rules indicate the senators in the room may vote on any bill at any time, even in the middle of an evacuation! 

So, the senators must be evacuated in a way that ensures that no party ever has an absolute majority. 

That is, it can never be the case after any evacuation step that __more than half__ of the senators in the senate room belong to the same party.

__Can you construct an evacuation plan? The senate is counting on you!__

__Input__

The first line of the input gives the number of test cases, $T$. 

$T$ test cases follow. Each test case consists of two lines. 

The first line contains a single integer $N$, the number of parties. 

The second line contains $N$ integers, $P_1, P_2, ..., P_N$, where $P_i$ represents the number of senators of the party named after the i-th letter of the alphabet.

__Output__

For each test case, output one line containing $Case \ \#x: y$, where 

- $x$ is the test case number (starting from 1) and 
- $y$ is the evacuation plan. 

The plan must be a space-separated list of instructions, in the order in which they are to be carried out, 

where each instruction is either one or two characters, representing the parties of the senators to evacuate in each step.

It is guaranteed that at least one valid evacuation plan will exist. 

If multiple evacuation plans are valid, you may output any of them.

__Limits__

$1 \leq T \leq 50$.

No party will have an absolute majority before the start of the evacuation.

$1 \leq P_i\leq1000$, for all i.

Time limit: 30 seconds per test set.

Memory limit: 1GB.

Test set 1 (Visible)

$2 \leq N \leq 3$.

sum of all $P_i \leq 9$.

Test set 2 (Hidden)

$2 \leq N \leq 26$.

sum of all $P_i \leq 1000$.


__Sample__

| - | Input | - | Output |
| :-: | :-: | :-: | :-: |
| $T$ | 4 | - | - |
| N | 2 | Evacuation Plan | `Case #1: AB BA` |
| $P_i$ | $2 \ 2$ | - | - |
| N | 3 | Evacuation Plan | `Case #2: AA BC C BA` |
| $P_i$ | $3 \ 2 \ 2$ | - | - |
| N | 3 | Evacuation Plan | `Case #3: C C AB` |
| $P_i$ | $1 \ 1 \ 2$ | - | - |
| N | 3 | Evacuation Plan | `Case #4: BA BB CA` |
| $P_i$ | $2 \ 3 \ 1$ | - | - |

The sample output displays one set of answers to the sample cases. Other answers may be possible.

In $Case \ \#1$, 

there are two senators from each of the parties A and B. 

If we remove one from each party every time, the perfect balance is maintained until evacuation is complete.

$Case \ \#2$ proceeds as follows:

Initially in the room: 3 A, 2 B, 2 C.

Evacuate AA. Still in the room: 1 A, 2 B, 2 C.

Evacuate BC. Still in the room: 1 A, 1 B, 1 C.

Evacuate C. Still in the room: 1 A, 1 B.

Evacuate AB. Evacuation complete!

Note that it would not be valid to begin the evacuation with BC, which would leave 3 A, 1 B, and 1 C in the room;

party A would have an absolute majority (3 out of 5 = 60%).

For $Case \ \#3$, note that CC AB would also be a valid answer, 

and C C AB is also valid even though it requires three evacuation steps instead of two.

## Task 2 Decision 

Let's try to create an interactive program for testing the main idea..

In [12]:
while True: 
    try:
        T = int(input("Indicate the number of test cases in the range [1, 50] "))
        if T in range(1,51):
            print("Thank you", flush=True)
            break 
        else:
            print("Please enter only integers in the mentioned range!", flush=True)
            continue
    except ValueError:
        print("Please enter only integers!", flush=True)
        
M = "Indicate the numbers of senators in political parties." + \
    "\n" + "Numbers are entered through a space." + \
    "\n" + "The number of senators in the parties is from 1 to 1000 people. "
A = numpy.array(list(string.ascii_uppercase)) 

paths = []
for i in range(T):
    while True:
        try:
            N = int(input("Indicate the number of political parties in the range [2, 26] "))
            S = input(M)
            S = numpy.array([int(s) for s in S.split()])
            condition1 = (len(S) == N) and (len(S[S < 1]) == 0) and (len(S[S > 1000]) == 0)
            condition2 = (N > 1) and (N < 27)
            
            if (condition1 and condition2):
                break
            elif len(S[S > S.sum()*0.5]) != 0:
                print("Please enter integers that no party has an absolute majority", flush=True)
                continue                
            else: 
                print("Please enter integers in the mentioned range!", flush=True)
                continue
        except ValueError:
            print("Please enter only integers!", flush=True)
            
    path = ''
    while S.sum() > 0:   
        i_max = numpy.where(S == S.max())[0]
    
        if S.sum() == 3:
            S[i_max[0]] -= 1
            path += A[i_max[0]] + ' '
        
        elif i_max.shape[0] == 1:
            S[i_max[0]] -= 2
            path += 2*A[i_max[0]] + ' '
        
        elif i_max.shape[0] > 1:
            S[i_max[0]] -= 1
            S[i_max[1]] -= 1        
            path += A[i_max[0]] + A[i_max[1]] + ' '
            
        print(S, ' - ', path)
    paths.append(path)
        
for i, el in enumerate(paths):  
    print('Case #{}: '.format(i+1), el)   

Indicate the number of test cases in the range [1, 50] 1
Thank you
Indicate the number of political parties in the range [2, 26] 28
Indicate the numbers of senators in political parties.
Numbers are entered through a space.
The number of senators in the parties is from 1 to 1000 people. 2 2 2 2 2 2
Please enter integers in the mentioned range!
Indicate the number of political parties in the range [2, 26] 10 15 12
Please enter only integers!
Indicate the number of political parties in the range [2, 26] 3
Indicate the numbers of senators in political parties.
Numbers are entered through a space.
The number of senators in the parties is from 1 to 1000 people. 10 15 12
[10 13 12]  -  BB 
[10 11 12]  -  BB BB 
[10 11 10]  -  BB BB CC 
[10  9 10]  -  BB BB CC BB 
[9 9 9]  -  BB BB CC BB AC 
[8 8 9]  -  BB BB CC BB AC AB 
[8 8 7]  -  BB BB CC BB AC AB CC 
[7 7 7]  -  BB BB CC BB AC AB CC AB 
[6 6 7]  -  BB BB CC BB AC AB CC AB AB 
[6 6 5]  -  BB BB CC BB AC AB CC AB AB CC 
[5 5 5]  -  BB BB C

The possible program as an answer.

In [11]:
T = int(input())
A = list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
for i in range(T):
    N = int(input())
    S = input()
    S = [int(s) for s in S.split()]
    path = ''
    while sum(S) > 0:   
        max_value = max(S)
        max_index = [i for i in range(N) if S[i] == max_value]
    
        if sum(S) == 3:
            S[max_index[0]] -= 1
            path += A[max_index[0]] + ' '
        
        elif len(max_index) == 1:
            S[max_index[0]] -= 2
            path += 2*A[max_index[0]] + ' '
        
        elif len(max_index) > 1:
            S[max_index[0]] -= 1
            S[max_index[1]] -= 1        
            path += A[max_index[0]] + A[max_index[1]] + ' ' 
          
    print('Case #{}: '.format(i+1), path)

4
2
2 2
Case #1:  AB AB 
3
3 2 2
Case #2:  AA BC A BC 
3
1 1 2
Case #3:  CC AB 
3
2 3 1
Case #4:  BB AA BC 


## Task 3 Steed 2: Cruise Control

__Problem__

Annie is a bus driver with a high-stress job. 

She tried to unwind by going on a Caribbean cruise, but that also turned out to be stressful, so she has recently taken up horseback riding.

Today, Annie is riding her horse to the east along a long and narrow one-way road that runs west to east. 

She is currently at kilometer 0 of the road, and her destination is at kilometer $D$; kilometers along the road are numbered from west to east.

There are $N$ other horses traveling east on the same road; all of them will go on traveling forever, and all of them are currently between Annie's horse and her destination. 

The i-th of these horses is initially at kilometer $K_i$ and is traveling at its maximum speed of $S_i$ kilometers per hour.

Horses are very polite, and a horse $H_1$ will not pass (move ahead of) another horse $H_2$ that started off ahead of $H_1$. 

(Two or more horses can share the same position for any amount of time; you may consider the horses to be single points.) 

Horses (other than Annie's) travel at their maximum speeds, except that whenever a horse $H_1$ catches up to another slower horse $H_2$, $H_1$ reduces its speed to match the speed of $H_2$.

Annie's horse, on the other hand, does not have a maximum speed and can travel at any speed that Annie chooses, as long as it does not pass another horse. 

To ensure a smooth ride for her and her horse, Annie wants to choose a single constant "cruise control" speed for her horse for the entire trip, from her current position to the destination, such that her horse will not pass any other horses. 

__What is the maximum such speed that she can choose?__

__Input__

The first line of the input gives the number of test cases, $T$; $T$ test cases follow. 

Each test case begins with two integers $D$ and $N$: 

- the destination position of all of the horses (in kilometers) and 
- the number of other horses on the road. 

Then, $N$ lines follow. 

The i-th of those lines has two integers $K_i$ and $S_i$: 

- the initial position (in kilometers) and 

- maximum speed (in kilometers per hour) of the i-th of the other horses on the road.

__Output__

For each test case, output one line containing $Case \ \#x: y$, where 

- $x$ is the test case number (starting from 1) and 

- $y$ is the maximum constant speed (in kilometers per hour) that Annie can use without colliding with other horses. 

$y$ will be considered correct if it is within an absolute or relative error of 10-6 of the correct answer. 

See the __FAQ__ for an explanation of what that means, and what formats of real numbers we accept.

__Limits__

$1 \leq T \leq 100$.

$0 < K_i < D \leq 109$, for all $i$.

$K_i \neq K_j$, for all $i \neq j$. (No two horses start in the same position.)

$1 \leq S_i \leq 10000$.

Time limit: 10 seconds per test set.

Memory limit: 1GB.

Test set 1 (Visible)

$1 \leq N \leq 2$.

Test set 2 (Hidden)

$1 \leq N \leq 1000$.